---
name: Build MimOS Image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 6" # Every Saturday at 7:00 UTC
  push:
    branches:
      - main
    paths:
      - mimos.containerfile
      - system/**
      - .github/workflows/build.yml
  workflow_dispatch:

env:
  IMAGE_DESC: "Mimolet's custom system image made to fit his needs for gaming and development."
  IMAGE_KEYWORDS: "linux,container,bootc,bazzite,kde,gaming,dev"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/115139719?v=4"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  REPO_OWNER: ${{ github.repository_owner }}
  FEDORA_VERSION: "44"
  BASE_IMAGE_REGISTRY: "ghcr.io/ublue-os"
  BASE_IMAGE_NAME: "bazzite-nvidia-open"
  BASE_IMAGE_TAG: "stable"
  # =====================================================================

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Show disk space
        run: sudo df -h

      - name: Check if /mnt is there
        id: check_mnt
        run: |
          if sudo mountpoint /mnt; then
            echo "mnt_is_there=1" >>$GITHUB_OUTPUT
          else
            echo "mnt_is_there=0" >>$GITHUB_OUTPUT
          fi

      - name: Free Disk Space (Ubuntu)
        if: ${{ steps.check_mnt.outputs.mnt_is_there == '1' }}
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Mount BTRFS for podman storage
        if: ${{ steps.check_mnt.outputs.mnt_is_there == '1' }}
        uses: ublue-os/container-storage-action@main
        with:
          target-dir: /var/lib/containers

      - name: Get lower-case repository owner
        id: repo_owner_case
        run: echo "lowercase=${REPO_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Define base variables
        id: base
        run: |
          PUSH_REGISTRY="ghcr.io/${{ steps.repo_owner_case.outputs.lowercase }}"
          BASE_IMAGE="${{ env.BASE_IMAGE_REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}"
          OUTPUT_IMAGE="${PUSH_REGISTRY}/${{ env.IMAGE_NAME }}"

          echo "push_registry=${PUSH_REGISTRY}"   >> "$GITHUB_OUTPUT"
          echo "base_image=${BASE_IMAGE}"         >> "$GITHUB_OUTPUT"
          echo "output_image=${OUTPUT_IMAGE}"     >> "$GITHUB_OUTPUT"

          echo "Generated the following:"
          cat $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Pull base image and find version
        id: labels
        run: |
          set -eo pipefail

          sudo podman pull ${{ steps.base.outputs.base_image }}
          sudo skopeo inspect docker://${{ steps.base.outputs.base_image }} > source.json

          UPSTREAM_TAG=$(jq -r '.Labels["org.opencontainers.image.version"]' source.json)
          if [ -z "$UPSTREAM_TAG" ] || [ "null" = "$UPSTREAM_TAG" ]; then
            echo "inspected image version must not be empty or null"
            exit 1
          fi
          UPSTREAM_TAG="${UPSTREAM_TAG%\.[0-9]}"

          if [ -n "${{ github.event.pull_request.number }}" ]; then
            VERSION="pr-${{ env.FEDORA_VERSION }}-${{ github.event.pull_request.number }}"
          else
            VERSION="${UPSTREAM_TAG}"
          fi

          echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          echo "Generated the following:"
          cat $GITHUB_OUTPUT

      - name: Prepare build args file
        run: |
          cat <<EOF >>build_args.txt
          BASE_IMAGE=${{ steps.base.outputs.base_image }}
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          IMAGE_VENDOR=${{ steps.repo_owner_case.outputs.lowercase }}
          IMAGE_BRANCH=${{ github.ref_name }}
          FEDORA_VERSION=${{ env.FEDORA_VERSION }}
          VERSION_TAG=${{ steps.labels.outputs.tag }}
          EOF

      - name: Restore DNF package cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /var/tmp/buildah-cache-*
          key: ${{ runner.os }}-${{ runner.arch }}-buildah-${{ env.FEDORA_VERSION }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-buildah-${{ env.FEDORA_VERSION }}-
            ${{ runner.os }}-${{ runner.arch }}-buildah-${{ env.FEDORA_VERSION }}

      - name: Build Image
        id: build_image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo -E buildah build \
            -f mimos.containerfile \
            --build-arg-file build_args.txt \
            --secret "id=GITHUB_TOKEN,env=GITHUB_TOKEN" \
            --tag raw-img .

      - name: Hack around permission issue caching
        run: sudo chmod 777 --recursive /var/tmp/buildah-cache-0

      - name: Save DNF package cache
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /var/tmp/buildah-cache-*
          key: ${{ runner.os }}-${{ runner.arch }}-buildah-${{ env.FEDORA_VERSION }}

      - name: Apply OCI Labels
        id: relabel
        env:
          IMAGE_LABELS: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.vendor=${{ steps.repo_owner_case.outputs.lowercase }}
        run: |
          version="${{ env.FEDORA_VERSION }}.$(date +%Y%m%d)"

          img=raw-img
          container=$(sudo buildah from $img)
          sudo buildah config --label "-" $container
          sudo buildah commit --identity-label=false --rm $container $img

          mapfile -t labels <<< "$IMAGE_LABELS"
          labels+=(
            "org.opencontainers.image.version=$version"
            "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            "ostree.bootable=true"
          )

          container=$(sudo buildah from $img)
          for line in "${labels[@]}"; do
            [ -z "$line" ] && continue
            sudo buildah config --label "$line" --annotation "$line" "$container"
          done
          sudo buildah commit --identity-label=false --rm $container $img

          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Run Rechunker
        id: rechunk
        run: |
          container=$(sudo buildah from raw-img)
          mnt=$(sudo buildah mount $container)
          sudo bash -c "rm -rf $mnt/run/.* $mnt/run/* $mnt/tmp/.* $mnt/tmp/*"
          sudo buildah umount $container
          sudo buildah commit --identity-label=false --rm $container raw-img

          sudo podman run --rm --privileged --volume /var/lib/containers:/var/lib/containers \
              localhost/raw-img \
              rpm-ostree compose build-chunked-oci \
              --bootc --max-layers 127 --format-version 2 \
              --from localhost/raw-img --output containers-storage:localhost/chunked-img
          sudo podman untag raw-img

          echo "ref=containers-storage:localhost/chunked-img" >> "$GITHUB_OUTPUT"

      - name: Generate tags
        id: generate-tags
        run: |
          VERSION_TAG="${{ steps.relabel.outputs.version }}"
          BUILD_TAGS=("latest" "${VERSION_TAG}")
          echo "alias_tags=${BUILD_TAGS[*]}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR
        id: push
        if: github.event_name != 'pull_request'
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        env:
          ALIAS_TAGS: ${{ steps.generate-tags.outputs.alias_tags }}
          OUTPUT_IMAGE: ${{ steps.base.outputs.output_image }}
          RECHUNK_REF: ${{ steps.rechunk.outputs.ref }}
          VERSION: ${{ steps.relabel.outputs.version }}
        with:
          max_attempts: 3
          retry_wait_seconds: 15
          timeout_minutes: 10
          command: |
            log_sum() { echo "$1" >> $GITHUB_STEP_SUMMARY; }
            log_sum '# Push to GHCR result'
            log_sum '```'

            dest_image="${OUTPUT_IMAGE}:${VERSION}"
            sudo skopeo copy ${RECHUNK_REF} docker://$dest_image
            log_sum "$dest_image"

            for tag in ${ALIAS_TAGS}; do
              dest_image="${OUTPUT_IMAGE}:$tag"
              sudo skopeo copy ${RECHUNK_REF} docker://$dest_image
              log_sum "$dest_image"
            done
            log_sum '```'

            digest=$(sudo skopeo inspect --format '{{.Digest}}' docker://${OUTPUT_IMAGE}:${VERSION})
            echo "digest=${digest}" >> $GITHUB_OUTPUT

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: "v2.6.1"

      - name: Sign container image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY --new-bundle-format=false \
            ${{ steps.base.outputs.output_image }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
